# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-01-04 07:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='brief_description',
            field=models.CharField(default='Really great book ', max_length=40),
        ),
    ]
